### ISSUE TITLE
10.7 Known Issues

### ISSUE THREAD

**Issue by oddstr13** [jellyfin/jellyfin-meta#1]
Migrated from @thornbill's [gist](https://gist.github.com/thornbill/e03ba28dec8637a33e755c74f58b8d86)

# 10.7 Hit List

## Bugs
* [x] Revert remote fonts
* [x] Changes to font and item sizes throughout ui? (maybe this is just due to the font falling back to DejaVu Sans)
* [ ] iOS streaming... is it finally fixed? jellyfin/jellyfin#3726
* [x] Are we going to restore the ability to have dynamic values stored for user preferences instead of this limited set? This is kind of a breaking change for 10.7 and I think there were discussions around fixing it awhile back. https://github.com/jellyfin/jellyfin/issues/4635
* [x] Android TV video playback fails
* [x] Video OSD disabled after changing subtitle option? jellyfin/jellyfin-web#2090
* [x] EPUB reader broken on desktop jellyfin/jellyfin-web#2095
* [x] PDF reader broken jellyfin/jellyfin-web#2092 jellyfin/jellyfin-web#2093
* [x] SubtitlesOctopus broken? jellyfin/jellyfin-web#2092
* [x] Need babel for old browser support jellyfin/jellyfin-web#2131
* [x] Need fallback for no webassembly support jellyfin/jellyfin-web#1881 (possibly fixed in jellyfin/jellyfin-web#2131)
* [x] Item IDs default to 0s instead of being excluded from response
* [x] Remove TVDB as default metadata provider
* [x] Remote search images are broken due to auth changes (images shown when identifying content) https://github.com/jellyfin/jellyfin-web/pull/2141
  * Should authentication also be required on `/Images/Remote`? **NOTE: Will require additional server and web changes**
* [ ] Library language not selected by default
* [x] Middle click is broken https://github.com/jellyfin/jellyfin-web/issues/1180 https://github.com/jellyfin/jellyfin-web/pull/2158
  * [x] Card links were broken by this change fixes in https://github.com/jellyfin/jellyfin-web/pull/2160 https://github.com/jellyfin/jellyfin-web/pull/2164
* [ ] People images don't show on item details screen until they are viewed in another context (person screen or edit images) Maybe this is intentional?
* [ ] Web sometimes hangs trying to reconnect using docker network ip address https://github.com/jellyfin/jellyfin-web/pull/2140
* [ ] Removing a version of a movie breaks collections the movie was part of jellyfin/jellyfin#4601
* [x] Android mobile app does not work because it's not compatible with the es6 changes yet jellyfin/jellyfin-android#240
* [x] Back button is broken in some browsers (Chrome, Firefox, Safari and Android app confirmed)
* [x] Library Order in preferences can not be saved jellyfin/jellyfin-web#2192
* [ ] OpenAPI specification missing jellyfin/jellyfin/issues/5426

## UI Issues
* [x] Improve item detail mobile layout (backdrops for People, Albums, etc.) https://github.com/jellyfin/jellyfin-web/pull/2246
* [x] Quick Connect polish https://github.com/jellyfin/jellyfin-web/pull/2155
* [ ] Button sizes are very inconsistent (very noticeable in admin dashboard) (partially fixed in https://github.com/jellyfin/jellyfin-web/pull/2128)
* [x] blurhash bleed through around images
* [ ] Video OSD large padding on bottom on mobile
* [x] Noto Sans should use locally installed version when available
* [ ] Poster position off sometimes (should be sticky?)
* [x] Plugin page lacks padding at top and icons are not centered in cards

## Related to Networking changes
* [x] Enabling IPv6 wildcard bind (to [::]) crashes Kestrel on startup; binding to a specific v6 addr is fine.
* [x] Disabling Autodiscovery does not disable listening on the autodiscovery port.
* [x] Client IP address is wrong by default when behind a proxy jellyfin/jellyfin#4670

DLNA is not IPv6 capable in 10.7 (is part of the next set of PR's), so enabling IPv6 may stop it from working. Recommended to leave IPv6 disabled if using DLNA.

## Python land
* [x] Jellyfin for Kodi not working jellyfin/jellyfin-kodi#431
* [ ] JellyCon user authentication failing

## MPV Shim Issues
* [x] Cannot cast to MPV Shim or to another copy of the web player.

Players aren't listed. Capabilities/Full post succeeded. Docker unstable as of 2020-11-26 15:15 EDT.
* [x] Initially I had problems with navigation not working, instead it just always seeks to beginning. I can't test at all now due to first issue.
* [ ] SyncPlay needs to be fixed/re-implemented in MPV Shim.
* [x] jellyfin/jellyfin#3931
* [x] jellyfin/jellyfin#3855

If there is progress on any of these, let me know via @ here or in Matrix. I would love to get everything working before release.

**Comment by nielsvanvelzen** [comment]
- [ ] jellyfin-web: the service worker registration doesn't work with baseurl (or web served in a subdirectory) since the path is hardcoded to '/serviceworker.js'

**Comment by Artiume** [comment]
- [ ] Jellyfin-API: start a transcode, transcode reason doesnt show. also, using the same session (no private window), start a second playback session such as direct play and the transcode playback data will bleed over to the direct play and vice versa

**Comment by ferferga** [comment]
# Server

MusicBrainz not working: **XMLException: Data at the root level is invalid** jellyfin/jellyfin#4631

**Comment by olskar** [comment]
Do you know if this one is possible to fix for 10.7? :)

![Screenshot_20201202-171747](https://user-images.githubusercontent.com/18314560/100899897-98fdc600-34c2-11eb-93e7-49f39e60f8fd.jpg)

**Comment by Artiume** [comment]
that's an issue upstream in ffmpeg, we've been attempting workarounds but nothing concrete yet

**Comment by ferferga** [comment]
Locking because this is, like the projects, for organization purposes on our own.

If you have an issue, feel free to open it in the relevant repo and we will take over it and label it accordingly 😇.

**Comment by Shadowghost** [comment]
Everything löabeled as `confirmed` on the repos:
* https://github.com/jellyfin/jellyfin-web/issues?q=is%3Aissue+is%3Aopen+label%3Aconfirmed
* https://github.com/jellyfin/jellyfin/issues?q=is%3Aissue+is%3Aopen+label%3Aconfirmed

With that one being especially annoying imho: https://github.com/jellyfin/jellyfin-web/issues/1824

**Comment by nyanmisaka** [comment]
Poster/image upload is broken. https://github.com/jellyfin/jellyfin/issues/3611

**Comment by nyanmisaka** [comment]
"Unexpected server response" iOS Infuse 6 is broken with 10.7. https://github.com/jellyfin/jellyfin/issues/4654

**Comment by Artiume** [comment]
[2020-12-05 06:41:45.323 +00:00] [WRN] [75] Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder: Error converting value.
System.FormatException: UserData is not a valid value for ItemFields.
 ---> System.ArgumentException: Requested value 'UserData' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Jellyfin.Api.ModelBinders.CommaDelimitedArrayModelBinder.GetParsedResult(IReadOnlyList`1 values, Type elementType, TypeConverter converter)

**Comment by Artiume** [comment]
[2020-12-05 06:40:10.223 +00:00] [WRN] [65] Jellyfin.Networking.Manager.NetworkManager: "meh IP/32": External request received, however, no WAN interface found.

**Comment by Artiume** [comment]
[2020-12-05 06:39:43.651 +00:00] [ERR] [109] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "The Open Movie Database"
System.ArgumentException: Unable to determine image file extension from mime type text/html
   at MediaBrowser.Providers.Manager.ImageSaver.GetStandardSavePath(BaseItem item, ImageType type, Nullable`1 imageIndex, String mimeType, Boolean saveLocally)
   at MediaBrowser.Providers.Manager.ImageSaver.GetSavePaths(BaseItem item, ImageType type, Nullable`1 imageIndex, String mimeType, Boolean saveLocally)
   at MediaBrowser.Providers.Manager.ImageSaver.SaveImage(BaseItem item, Stream source, String mimeType, ImageType type, Nullable`1 imageIndex, Nullable`1 saveLocallyWithMedia, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.DownloadImage(BaseItem item, LibraryOptions libraryOptions, IRemoteImageProvider provider, RefreshResult result, IEnumerable`1 images, Int32 minWidth, ImageType type, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.DownloadImage(BaseItem item, LibraryOptions libraryOptions, IRemoteImageProvider provider, RefreshResult result, IEnumerable`1 images, Int32 minWidth, ImageType type, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ItemImageProvider.RefreshFromProvider(BaseItem item, LibraryOptions libraryOptions, IRemoteImageProvider provider, ImageRefreshOptions refreshOptions, TypeOptions savedOptions, Int32 backdropLimit, Int32 screenshotLimit, ICollection`1 downloadedImages, RefreshResult result, CancellationToken cancellationToken)

**Comment by Artiume** [comment]
tvdb as a plugin option is missing

**Comment by nyanmisaka** [comment]
When Tone mapping with Intel VAAPI, the graphical subtitle burn-in is unavailable.

**Comment by Artiume** [comment]
[2020-12-05 06:58:19.821 +00:00] [INF] [96] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Killing ffmpeg process
[2020-12-05 06:58:19.821 +00:00] [ERR] [96] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: ffmpeg image extraction failed for file:"/media/movies/B/Batman and Robin (1949)/Batman and Robin (1949).mkv"
[2020-12-05 06:58:19.822 +00:00] [ERR] [96] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: I-frame or HDR image extraction failed, will attempt with I-frame extraction disabled. Input: "file:\"/media/movies/B/Batman and Robin (1949)/Batman and Robin (1949).mkv\""
System.Exception: ffmpeg image extraction failed for file:"/media/movies/B/Batman and Robin (1949)/Batman and Robin (1949).mkv"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, Boolean allowTonemap, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String inputFile, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaSourceInfo mediaSource, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, CancellationToken cancellationToken)

**Comment by Artiume** [comment]
Still performing a scan so that might have something to do with it but Playback is acting oddly. It's treating all files as though they're livetv. When playback first starts, the entire film length is approximately 30 seconds and will slowly increment as playback continues.

**Comment by BaronGreenback** [comment]
> [2020-12-05 06:40:10.223 +00:00] [WRN] [65] Jellyfin.Networking.Manager.NetworkManager: "meh IP/32": External request received, however, no WAN interface found.
Fixed : https://github.com/jellyfin/jellyfin/pull/4678

**Comment by Shadowghost** [comment]
https://github.com/jellyfin/jellyfin/issues/4681

**Comment by Shadowghost** [comment]
https://github.com/jellyfin/jellyfin/issues/4682

**Comment by iwalton3** [comment]
Looks like MPV Shim is now working again with basic features. SyncPlay needs to be reworked, as expected. I will likely drop SyncPlay compatibility with pre-10.7.0 servers, as the web client (Desktop Mode) won't support it anyways.

**Comment by thornbill** [comment]
It's probably time to close this given a 10.8 RC is pending. 🙃
